import Footer from '@/components/Footer'
import { GSAP } from '@/components/shared/GSAP'
import { Lenis } from '@/components/shared/Lenis'
import { client } from '@/sanity/client'
import { settingsQuery } from '@/sanity/queries'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { type Settings } from '../../sanity.types'
import './globals.css'
const options = { next: { revalidate: 30 } }

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const settings = await client.fetch<Settings>(settingsQuery, {}, options)
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <Lenis />
        <GSAP />
        <div className="flex min-h-screen flex-col justify-start bg-white text-black">
          <main className="grow" id="main-content">
            {children}
          </main>
          <Footer data={settings} />
        </div>
      </body>
    </html>
  )
}
